services:
  web:
    platform: linux/amd64
    build: .
    ports:
      - "8888:80"
      - "8443:443"
      - "3306:3306"
    volumes:
      - ./htdocs:/opt/lampp/htdocs
      - ./logs:/opt/lampp/logs
    environment:
      - TZ=Asia/Shanghai