services:
  web:
    build: .
    platform: linux/amd64
    ports:
      - "8888:80"
    volumes:
      - ./htdocs:/var/www/html
      - ./php.ini:/usr/local/etc/php/php.ini
    environment:
      - APACHE_RUN_USER=www-data
      - APACHE_RUN_GROUP=www-data
      - TZ=Asia/Shanghai
    depends_on:
      - db
    networks:
      - xampp-network

  db:
    image: mariadb:5.5
    platform: linux/amd64
    command: --skip-name-resolve --default-storage-engine=MyISAM
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: xampp
      MYSQL_TCP_PORT: 3306
    volumes:
      - db_data:/var/lib/mysql
      - ./my.cnf:/etc/mysql/my.cnf
    ports:
      - "3306:3306"
    networks:
      - xampp-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:4.9
    platform: linux/amd64
    ports:
      - "8889:80"
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: ""
      APACHE_SERVER_NAME: localhost
    depends_on:
      - db
    networks:
      - xampp-network

networks:
  xampp-network:
    driver: bridge

volumes:
  db_data: